name: "Documentation: Preview"

on:
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/docs-preview.yml'

jobs:
  deploy:
    name: Deploy to Cloudflare
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        working-directory: docs
        run: bun install

      - name: Build documentation
        working-directory: docs
        run: bun run build

      - name: Deploy to Cloudflare
        id: versions_upload
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDLFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: docs
          packageManager: bun
          command: versions upload --message "${{ github.sha }}"
          wranglerVersion: 4.19.2

      - name: Get Version ID
        shell: bash
        id: version_id
        run: |
            version_id=$(echo '${{ steps.versions_upload.outputs.command-output }}' | grep "Worker Version ID" | awk '{print $4}')
            echo "version_id=$version_id" >> $GITHUB_OUTPUT

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Your preview deployment is available at https://${{ steps.version_id.outputs.version_id }}-dhd-documentation.korora-tech.workers.dev
