name: Documentation Preview

on:
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/docs-preview.yml'

jobs:
  preview:
    name: Build and Preview
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        working-directory: docs
        run: bun install

      - name: Build documentation
        working-directory: docs
        run: bun run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-preview
          path: docs/dist

      - name: Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '📚 Documentation preview build completed! The artifacts are available in the workflow run.'
            })